<?php
// define variables
define('PASSWD_ROOT', realpath(__DIR__. DIRECTORY_SEPARATOR. '..'). DIRECTORY_SEPARATOR);
define('PASSWD_SECRET', PASSWD_ROOT. 'secret'. DIRECTORY_SEPARATOR);
define('PASSWD_LAYOUT', PASSWD_ROOT. 'src'. DIRECTORY_SEPARATOR. 'layout'. DIRECTORY_SEPARATOR);